//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATDAILY
    {
        public int ID { get; set; }
        public int DEPT_ID { get; set; }
        public int DOCTOR_ID { get; set; }
        public string DOCTOR_NAME { get; set; }
        public Nullable<int> CONSULT_PEOPLE_COUNT { get; set; }
        public Nullable<int> CONSULT_QUESTION_COUNT { get; set; }
        public System.DateTime STAT_TIME { get; set; }
    }
}
