// <auto-generated />
namespace Lee.PostgreSQL.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11));
        
        string IMigrationMetadata.Id
        {
            get { return "201806271141168_1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
